# Generated by Django 3.1.1 on 2020-10-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_auto_20201017_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(to='task_manager.Tag'),
        ),
    ]
