# Generated by Django 3.1.1 on 2020-10-17 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0009_auto_20201017_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
