# Generated by Django 3.1.1 on 2020-10-31 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0011_tag_task_taskstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='task_manager.taskstatus'),
        ),
    ]
