name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Collect static
      run: |
        poetry run python manage.py collectstatic
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
    - name: Lint with flake8
      run: |
        make lint
    - name: Test
      run: |
        make test_coverage
      env:
        DB_ENGINE: SQLite
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
    - name: Publish code coverage report
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: make test-coverage-report-xml
